version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/Flask-App
permissions:
  - object: /var/www/html/Flask-App
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
